export default [
  {
    id: "cs",
    title: "Computer Science Materials",
    description: "These are the Computer Science Docs.",
    docs: [
      "/cs/doc1.pdf",
      "/cs/doc2.pdf",
      "/cs/doc3.pdf",
      "/cs/doc4.pdf",
      "/cs/doc5.pdf",
      "/cs/doc6.pdf",
      "/cs/doc7.pdf",
      "/cs/doc8.pdf",
    ],
  },
  {
    id: "physics",
    title: "Physics Materials",
    description: "These are the Physics Docs.",
    docs: [
      "/physics/doc1.pdf",
      "/physics/doc2.pdf",
      "/physics/doc3.pdf",
      "/physics/doc4.pdf",
      "/physics/doc5.pdf",
      "/physics/doc6.pdf",
      "/physics/doc7.pdf",
      "/physics/doc8.pdf",
    ],
  },
  {
    id: "law",
    title: "Law Materials",
    description: "These are the Law Docs.",
    docs: [
      "/law/doc1.pdf",
      "/law/doc2.pdf",
      "/law/doc3.pdf",
      "/law/doc4.pdf",
      "/law/doc5.pdf",
      "/law/doc6.pdf",
      "/law/doc7.pdf",
      "/law/doc8.pdf",
    ],
  },
  {
    id: "acc",
    title: "Accounting Materials",
    description: "These are the Accounting Docs.",
    docs: [
      "/acc/doc1.pdf",
      "/acc/doc2.pdf",
      "/acc/doc3.pdf",
      "/acc/doc4.pdf",
      "/acc/doc5.pdf",
      "/acc/doc6.pdf",
      "/acc/doc7.pdf",
      "/acc/doc8.pdf",
    ],
  },
  {
    id: "eco",
    title: "Economics Materials",
    description: "These are the Economics Docs.",
    docs: [
      "/eco/doc1.pdf",
      "/eco/doc2.pdf",
      "/eco/doc3.pdf",
      "/eco/doc4.pdf",
      "/eco/doc5.pdf",
      "/eco/doc6.pdf",
      "/eco/doc7.pdf",
      "/eco/doc8.pdf",
    ],
  },
  {
    id: "elec",
    title: "Electrical Eng. Materials",
    description: "These are the Electrical  Docs.",
    docs: [
      "/elec/doc1.pdf",
      "/elec/doc2.pdf",
      "/elec/doc3.pdf",
      "/elec/doc4.pdf",
      "/elec/doc5.pdf",
      "/elec/doc6.pdf",
      "/elec/doc7.pdf",
      "/elec/doc8.pdf",
    ],
  },
];
